iRegisterCommand("roll", function(source, args, rawCommand)
    local playerId = GetPlayerServerId(PlayerId()) 
    local roll = math.random(1, 6) 
    TriggerServerEvent("sendRollMessage", roll, playerId)
end, false)
